// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: bandidos_bang.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb_game_100042";

/** Códigos de comando */
export enum cmdCode {
  CMD_CODE_UNKNOWN = 0,
  /** MDM_GAME_NOTIFY - 0xB4 */
  MDM_GAME_NOTIFY = 180,
  /** ASS_GAME_ROLL - 0x50 */
  ASS_GAME_ROLL = 80,
  UNRECOGNIZED = -1,
}

export function cmdCodeFromJSON(object: any): cmdCode {
  switch (object) {
    case 0:
    case "CMD_CODE_UNKNOWN":
      return cmdCode.CMD_CODE_UNKNOWN;
    case 180:
    case "MDM_GAME_NOTIFY":
      return cmdCode.MDM_GAME_NOTIFY;
    case 80:
    case "ASS_GAME_ROLL":
      return cmdCode.ASS_GAME_ROLL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return cmdCode.UNRECOGNIZED;
  }
}

export function cmdCodeToJSON(object: cmdCode): string {
  switch (object) {
    case cmdCode.CMD_CODE_UNKNOWN:
      return "CMD_CODE_UNKNOWN";
    case cmdCode.MDM_GAME_NOTIFY:
      return "MDM_GAME_NOTIFY";
    case cmdCode.ASS_GAME_ROLL:
      return "ASS_GAME_ROLL";
    case cmdCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Códigos de erro */
export enum errorCode {
  ERROR_CODE_UNKNOWN = 0,
  ROLL_BET_INVALIDE = 1,
  ROLL_SCORE_NOT_ENOUGH = 2,
  ROLL_MODE_IS_ERROR = 3,
  ROLL_TYPE_ERROR = 4,
  UNRECOGNIZED = -1,
}

export function errorCodeFromJSON(object: any): errorCode {
  switch (object) {
    case 0:
    case "ERROR_CODE_UNKNOWN":
      return errorCode.ERROR_CODE_UNKNOWN;
    case 1:
    case "ROLL_BET_INVALIDE":
      return errorCode.ROLL_BET_INVALIDE;
    case 2:
    case "ROLL_SCORE_NOT_ENOUGH":
      return errorCode.ROLL_SCORE_NOT_ENOUGH;
    case 3:
    case "ROLL_MODE_IS_ERROR":
      return errorCode.ROLL_MODE_IS_ERROR;
    case 4:
    case "ROLL_TYPE_ERROR":
      return errorCode.ROLL_TYPE_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return errorCode.UNRECOGNIZED;
  }
}

export function errorCodeToJSON(object: errorCode): string {
  switch (object) {
    case errorCode.ERROR_CODE_UNKNOWN:
      return "ERROR_CODE_UNKNOWN";
    case errorCode.ROLL_BET_INVALIDE:
      return "ROLL_BET_INVALIDE";
    case errorCode.ROLL_SCORE_NOT_ENOUGH:
      return "ROLL_SCORE_NOT_ENOUGH";
    case errorCode.ROLL_MODE_IS_ERROR:
      return "ROLL_MODE_IS_ERROR";
    case errorCode.ROLL_TYPE_ERROR:
      return "ROLL_TYPE_ERROR";
    case errorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Informações gerais do jogo */
export interface scGameInfo {
  gameStation: number;
  lineCount: number;
  defaultBet: number;
  playerScore: number;
  gameInfo: scGameRoll | undefined;
}

/** Requisição do cliente para “rodar” o jogo */
export interface csGameRoll {
  betScore: number;
  type: number;
}

/** Resposta do servidor ao “roll” */
export interface scGameRoll {
  currentMode: number;
  nextMode: number;
  winScore: number;
  winType: number;
  freeCount: number;
  allFreeTimes: number;
  totalFreeWinScore: number;
  userScore: number;
  betScore: number;
  resultCells: number[];
  multiples: number;
  baseScore: number;
  type: number;
}

function createBasescGameInfo(): scGameInfo {
  return { gameStation: 0, lineCount: 0, defaultBet: 0, playerScore: 0, gameInfo: undefined };
}

export const scGameInfo: MessageFns<scGameInfo> = {
  encode(message: scGameInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.gameStation !== 0) {
      writer.uint32(8).int32(message.gameStation);
    }
    if (message.lineCount !== 0) {
      writer.uint32(16).int32(message.lineCount);
    }
    if (message.defaultBet !== 0) {
      writer.uint32(24).int64(message.defaultBet);
    }
    if (message.playerScore !== 0) {
      writer.uint32(32).int64(message.playerScore);
    }
    if (message.gameInfo !== undefined) {
      scGameRoll.encode(message.gameInfo, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scGameInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescGameInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.gameStation = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lineCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.defaultBet = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.playerScore = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.gameInfo = scGameRoll.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scGameInfo {
    return {
      gameStation: isSet(object.gameStation) ? globalThis.Number(object.gameStation) : 0,
      lineCount: isSet(object.lineCount) ? globalThis.Number(object.lineCount) : 0,
      defaultBet: isSet(object.defaultBet) ? globalThis.Number(object.defaultBet) : 0,
      playerScore: isSet(object.playerScore) ? globalThis.Number(object.playerScore) : 0,
      gameInfo: isSet(object.gameInfo) ? scGameRoll.fromJSON(object.gameInfo) : undefined,
    };
  },

  toJSON(message: scGameInfo): unknown {
    const obj: any = {};
    if (message.gameStation !== 0) {
      obj.gameStation = Math.round(message.gameStation);
    }
    if (message.lineCount !== 0) {
      obj.lineCount = Math.round(message.lineCount);
    }
    if (message.defaultBet !== 0) {
      obj.defaultBet = Math.round(message.defaultBet);
    }
    if (message.playerScore !== 0) {
      obj.playerScore = Math.round(message.playerScore);
    }
    if (message.gameInfo !== undefined) {
      obj.gameInfo = scGameRoll.toJSON(message.gameInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scGameInfo>, I>>(base?: I): scGameInfo {
    return scGameInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scGameInfo>, I>>(object: I): scGameInfo {
    const message = createBasescGameInfo();
    message.gameStation = object.gameStation ?? 0;
    message.lineCount = object.lineCount ?? 0;
    message.defaultBet = object.defaultBet ?? 0;
    message.playerScore = object.playerScore ?? 0;
    message.gameInfo = (object.gameInfo !== undefined && object.gameInfo !== null)
      ? scGameRoll.fromPartial(object.gameInfo)
      : undefined;
    return message;
  },
};

function createBasecsGameRoll(): csGameRoll {
  return { betScore: 0, type: 0 };
}

export const csGameRoll: MessageFns<csGameRoll> = {
  encode(message: csGameRoll, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.betScore !== 0) {
      writer.uint32(8).int64(message.betScore);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csGameRoll {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsGameRoll();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.betScore = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csGameRoll {
    return {
      betScore: isSet(object.betScore) ? globalThis.Number(object.betScore) : 0,
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
    };
  },

  toJSON(message: csGameRoll): unknown {
    const obj: any = {};
    if (message.betScore !== 0) {
      obj.betScore = Math.round(message.betScore);
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csGameRoll>, I>>(base?: I): csGameRoll {
    return csGameRoll.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csGameRoll>, I>>(object: I): csGameRoll {
    const message = createBasecsGameRoll();
    message.betScore = object.betScore ?? 0;
    message.type = object.type ?? 0;
    return message;
  },
};

function createBasescGameRoll(): scGameRoll {
  return {
    currentMode: 0,
    nextMode: 0,
    winScore: 0,
    winType: 0,
    freeCount: 0,
    allFreeTimes: 0,
    totalFreeWinScore: 0,
    userScore: 0,
    betScore: 0,
    resultCells: [],
    multiples: 0,
    baseScore: 0,
    type: 0,
  };
}

export const scGameRoll: MessageFns<scGameRoll> = {
  encode(message: scGameRoll, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currentMode !== 0) {
      writer.uint32(8).int32(message.currentMode);
    }
    if (message.nextMode !== 0) {
      writer.uint32(16).int32(message.nextMode);
    }
    if (message.winScore !== 0) {
      writer.uint32(24).int64(message.winScore);
    }
    if (message.winType !== 0) {
      writer.uint32(32).int32(message.winType);
    }
    if (message.freeCount !== 0) {
      writer.uint32(40).int32(message.freeCount);
    }
    if (message.allFreeTimes !== 0) {
      writer.uint32(48).int32(message.allFreeTimes);
    }
    if (message.totalFreeWinScore !== 0) {
      writer.uint32(56).int64(message.totalFreeWinScore);
    }
    if (message.userScore !== 0) {
      writer.uint32(64).int64(message.userScore);
    }
    if (message.betScore !== 0) {
      writer.uint32(72).int64(message.betScore);
    }
    writer.uint32(90).fork();
    for (const v of message.resultCells) {
      writer.int32(v);
    }
    writer.join();
    if (message.multiples !== 0) {
      writer.uint32(96).int64(message.multiples);
    }
    if (message.baseScore !== 0) {
      writer.uint32(104).int64(message.baseScore);
    }
    if (message.type !== 0) {
      writer.uint32(112).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scGameRoll {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescGameRoll();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.currentMode = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.nextMode = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.winScore = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.winType = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.freeCount = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.allFreeTimes = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalFreeWinScore = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.userScore = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.betScore = longToNumber(reader.int64());
          continue;
        }
        case 11: {
          if (tag === 88) {
            message.resultCells.push(reader.int32());

            continue;
          }

          if (tag === 90) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.resultCells.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.multiples = longToNumber(reader.int64());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.baseScore = longToNumber(reader.int64());
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scGameRoll {
    return {
      currentMode: isSet(object.currentMode) ? globalThis.Number(object.currentMode) : 0,
      nextMode: isSet(object.nextMode) ? globalThis.Number(object.nextMode) : 0,
      winScore: isSet(object.winScore) ? globalThis.Number(object.winScore) : 0,
      winType: isSet(object.winType) ? globalThis.Number(object.winType) : 0,
      freeCount: isSet(object.freeCount) ? globalThis.Number(object.freeCount) : 0,
      allFreeTimes: isSet(object.allFreeTimes) ? globalThis.Number(object.allFreeTimes) : 0,
      totalFreeWinScore: isSet(object.totalFreeWinScore) ? globalThis.Number(object.totalFreeWinScore) : 0,
      userScore: isSet(object.userScore) ? globalThis.Number(object.userScore) : 0,
      betScore: isSet(object.betScore) ? globalThis.Number(object.betScore) : 0,
      resultCells: globalThis.Array.isArray(object?.resultCells)
        ? object.resultCells.map((e: any) => globalThis.Number(e))
        : [],
      multiples: isSet(object.multiples) ? globalThis.Number(object.multiples) : 0,
      baseScore: isSet(object.baseScore) ? globalThis.Number(object.baseScore) : 0,
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
    };
  },

  toJSON(message: scGameRoll): unknown {
    const obj: any = {};
    if (message.currentMode !== 0) {
      obj.currentMode = Math.round(message.currentMode);
    }
    if (message.nextMode !== 0) {
      obj.nextMode = Math.round(message.nextMode);
    }
    if (message.winScore !== 0) {
      obj.winScore = Math.round(message.winScore);
    }
    if (message.winType !== 0) {
      obj.winType = Math.round(message.winType);
    }
    if (message.freeCount !== 0) {
      obj.freeCount = Math.round(message.freeCount);
    }
    if (message.allFreeTimes !== 0) {
      obj.allFreeTimes = Math.round(message.allFreeTimes);
    }
    if (message.totalFreeWinScore !== 0) {
      obj.totalFreeWinScore = Math.round(message.totalFreeWinScore);
    }
    if (message.userScore !== 0) {
      obj.userScore = Math.round(message.userScore);
    }
    if (message.betScore !== 0) {
      obj.betScore = Math.round(message.betScore);
    }
    if (message.resultCells?.length) {
      obj.resultCells = message.resultCells.map((e) => Math.round(e));
    }
    if (message.multiples !== 0) {
      obj.multiples = Math.round(message.multiples);
    }
    if (message.baseScore !== 0) {
      obj.baseScore = Math.round(message.baseScore);
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scGameRoll>, I>>(base?: I): scGameRoll {
    return scGameRoll.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scGameRoll>, I>>(object: I): scGameRoll {
    const message = createBasescGameRoll();
    message.currentMode = object.currentMode ?? 0;
    message.nextMode = object.nextMode ?? 0;
    message.winScore = object.winScore ?? 0;
    message.winType = object.winType ?? 0;
    message.freeCount = object.freeCount ?? 0;
    message.allFreeTimes = object.allFreeTimes ?? 0;
    message.totalFreeWinScore = object.totalFreeWinScore ?? 0;
    message.userScore = object.userScore ?? 0;
    message.betScore = object.betScore ?? 0;
    message.resultCells = object.resultCells?.map((e) => e) || [];
    message.multiples = object.multiples ?? 0;
    message.baseScore = object.baseScore ?? 0;
    message.type = object.type ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
