// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: pb_lobby_notice.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb_lobby_notice";

export interface noticeMarqueeMsg {
  message: string;
  level: number;
  showtimes: number;
  frequency: number;
  starttime: string;
  endtime: string;
}

export interface scNoticeMarquee {
  marqueelist: noticeMarqueeMsg[];
}

export interface noticeWindowMsg {
  id: number;
  level: number;
  title: string;
  message: string;
  showtype: number;
}

export interface scNoticeWindow {
  windowlist: noticeWindowMsg[];
}

function createBasenoticeMarqueeMsg(): noticeMarqueeMsg {
  return { message: "", level: 0, showtimes: 0, frequency: 0, starttime: "", endtime: "" };
}

export const noticeMarqueeMsg: MessageFns<noticeMarqueeMsg> = {
  encode(message: noticeMarqueeMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.level !== 0) {
      writer.uint32(16).int32(message.level);
    }
    if (message.showtimes !== 0) {
      writer.uint32(24).int32(message.showtimes);
    }
    if (message.frequency !== 0) {
      writer.uint32(32).int32(message.frequency);
    }
    if (message.starttime !== "") {
      writer.uint32(42).string(message.starttime);
    }
    if (message.endtime !== "") {
      writer.uint32(50).string(message.endtime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): noticeMarqueeMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasenoticeMarqueeMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.showtimes = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.frequency = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.starttime = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.endtime = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): noticeMarqueeMsg {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      showtimes: isSet(object.showtimes) ? globalThis.Number(object.showtimes) : 0,
      frequency: isSet(object.frequency) ? globalThis.Number(object.frequency) : 0,
      starttime: isSet(object.starttime) ? globalThis.String(object.starttime) : "",
      endtime: isSet(object.endtime) ? globalThis.String(object.endtime) : "",
    };
  },

  toJSON(message: noticeMarqueeMsg): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.showtimes !== 0) {
      obj.showtimes = Math.round(message.showtimes);
    }
    if (message.frequency !== 0) {
      obj.frequency = Math.round(message.frequency);
    }
    if (message.starttime !== "") {
      obj.starttime = message.starttime;
    }
    if (message.endtime !== "") {
      obj.endtime = message.endtime;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<noticeMarqueeMsg>, I>>(base?: I): noticeMarqueeMsg {
    return noticeMarqueeMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<noticeMarqueeMsg>, I>>(object: I): noticeMarqueeMsg {
    const message = createBasenoticeMarqueeMsg();
    message.message = object.message ?? "";
    message.level = object.level ?? 0;
    message.showtimes = object.showtimes ?? 0;
    message.frequency = object.frequency ?? 0;
    message.starttime = object.starttime ?? "";
    message.endtime = object.endtime ?? "";
    return message;
  },
};

function createBasescNoticeMarquee(): scNoticeMarquee {
  return { marqueelist: [] };
}

export const scNoticeMarquee: MessageFns<scNoticeMarquee> = {
  encode(message: scNoticeMarquee, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.marqueelist) {
      noticeMarqueeMsg.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scNoticeMarquee {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescNoticeMarquee();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.marqueelist.push(noticeMarqueeMsg.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scNoticeMarquee {
    return {
      marqueelist: globalThis.Array.isArray(object?.marqueelist)
        ? object.marqueelist.map((e: any) => noticeMarqueeMsg.fromJSON(e))
        : [],
    };
  },

  toJSON(message: scNoticeMarquee): unknown {
    const obj: any = {};
    if (message.marqueelist?.length) {
      obj.marqueelist = message.marqueelist.map((e) => noticeMarqueeMsg.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scNoticeMarquee>, I>>(base?: I): scNoticeMarquee {
    return scNoticeMarquee.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scNoticeMarquee>, I>>(object: I): scNoticeMarquee {
    const message = createBasescNoticeMarquee();
    message.marqueelist = object.marqueelist?.map((e) => noticeMarqueeMsg.fromPartial(e)) || [];
    return message;
  },
};

function createBasenoticeWindowMsg(): noticeWindowMsg {
  return { id: 0, level: 0, title: "", message: "", showtype: 0 };
}

export const noticeWindowMsg: MessageFns<noticeWindowMsg> = {
  encode(message: noticeWindowMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.level !== 0) {
      writer.uint32(16).int32(message.level);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    if (message.message !== "") {
      writer.uint32(34).string(message.message);
    }
    if (message.showtype !== 0) {
      writer.uint32(40).int32(message.showtype);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): noticeWindowMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasenoticeWindowMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.showtype = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): noticeWindowMsg {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      showtype: isSet(object.showtype) ? globalThis.Number(object.showtype) : 0,
    };
  },

  toJSON(message: noticeWindowMsg): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.showtype !== 0) {
      obj.showtype = Math.round(message.showtype);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<noticeWindowMsg>, I>>(base?: I): noticeWindowMsg {
    return noticeWindowMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<noticeWindowMsg>, I>>(object: I): noticeWindowMsg {
    const message = createBasenoticeWindowMsg();
    message.id = object.id ?? 0;
    message.level = object.level ?? 0;
    message.title = object.title ?? "";
    message.message = object.message ?? "";
    message.showtype = object.showtype ?? 0;
    return message;
  },
};

function createBasescNoticeWindow(): scNoticeWindow {
  return { windowlist: [] };
}

export const scNoticeWindow: MessageFns<scNoticeWindow> = {
  encode(message: scNoticeWindow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.windowlist) {
      noticeWindowMsg.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scNoticeWindow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescNoticeWindow();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.windowlist.push(noticeWindowMsg.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scNoticeWindow {
    return {
      windowlist: globalThis.Array.isArray(object?.windowlist)
        ? object.windowlist.map((e: any) => noticeWindowMsg.fromJSON(e))
        : [],
    };
  },

  toJSON(message: scNoticeWindow): unknown {
    const obj: any = {};
    if (message.windowlist?.length) {
      obj.windowlist = message.windowlist.map((e) => noticeWindowMsg.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scNoticeWindow>, I>>(base?: I): scNoticeWindow {
    return scNoticeWindow.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scNoticeWindow>, I>>(object: I): scNoticeWindow {
    const message = createBasescNoticeWindow();
    message.windowlist = object.windowlist?.map((e) => noticeWindowMsg.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
