// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: pb_lobby_personal.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb_lobby_personal";

export interface csModifyNikenameMsg {
  name: string;
}

export interface csModifyLogoMsg {
  logo: number;
}

export interface csBaseInfo {
}

export interface scBaseInfo {
  modifyLogoTimes: number;
  modifyNameTimes: number;
}

function createBasecsModifyNikenameMsg(): csModifyNikenameMsg {
  return { name: "" };
}

export const csModifyNikenameMsg: MessageFns<csModifyNikenameMsg> = {
  encode(message: csModifyNikenameMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csModifyNikenameMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsModifyNikenameMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csModifyNikenameMsg {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: csModifyNikenameMsg): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csModifyNikenameMsg>, I>>(base?: I): csModifyNikenameMsg {
    return csModifyNikenameMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csModifyNikenameMsg>, I>>(object: I): csModifyNikenameMsg {
    const message = createBasecsModifyNikenameMsg();
    message.name = object.name ?? "";
    return message;
  },
};

function createBasecsModifyLogoMsg(): csModifyLogoMsg {
  return { logo: 0 };
}

export const csModifyLogoMsg: MessageFns<csModifyLogoMsg> = {
  encode(message: csModifyLogoMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.logo !== 0) {
      writer.uint32(8).int32(message.logo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csModifyLogoMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsModifyLogoMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.logo = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csModifyLogoMsg {
    return { logo: isSet(object.logo) ? globalThis.Number(object.logo) : 0 };
  },

  toJSON(message: csModifyLogoMsg): unknown {
    const obj: any = {};
    if (message.logo !== 0) {
      obj.logo = Math.round(message.logo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csModifyLogoMsg>, I>>(base?: I): csModifyLogoMsg {
    return csModifyLogoMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csModifyLogoMsg>, I>>(object: I): csModifyLogoMsg {
    const message = createBasecsModifyLogoMsg();
    message.logo = object.logo ?? 0;
    return message;
  },
};

function createBasecsBaseInfo(): csBaseInfo {
  return {};
}

export const csBaseInfo: MessageFns<csBaseInfo> = {
  encode(_: csBaseInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csBaseInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsBaseInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): csBaseInfo {
    return {};
  },

  toJSON(_: csBaseInfo): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<csBaseInfo>, I>>(base?: I): csBaseInfo {
    return csBaseInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csBaseInfo>, I>>(_: I): csBaseInfo {
    const message = createBasecsBaseInfo();
    return message;
  },
};

function createBasescBaseInfo(): scBaseInfo {
  return { modifyLogoTimes: 0, modifyNameTimes: 0 };
}

export const scBaseInfo: MessageFns<scBaseInfo> = {
  encode(message: scBaseInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modifyLogoTimes !== 0) {
      writer.uint32(8).int32(message.modifyLogoTimes);
    }
    if (message.modifyNameTimes !== 0) {
      writer.uint32(16).int32(message.modifyNameTimes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scBaseInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescBaseInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.modifyLogoTimes = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.modifyNameTimes = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scBaseInfo {
    return {
      modifyLogoTimes: isSet(object.modifyLogoTimes) ? globalThis.Number(object.modifyLogoTimes) : 0,
      modifyNameTimes: isSet(object.modifyNameTimes) ? globalThis.Number(object.modifyNameTimes) : 0,
    };
  },

  toJSON(message: scBaseInfo): unknown {
    const obj: any = {};
    if (message.modifyLogoTimes !== 0) {
      obj.modifyLogoTimes = Math.round(message.modifyLogoTimes);
    }
    if (message.modifyNameTimes !== 0) {
      obj.modifyNameTimes = Math.round(message.modifyNameTimes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scBaseInfo>, I>>(base?: I): scBaseInfo {
    return scBaseInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scBaseInfo>, I>>(object: I): scBaseInfo {
    const message = createBasescBaseInfo();
    message.modifyLogoTimes = object.modifyLogoTimes ?? 0;
    message.modifyNameTimes = object.modifyNameTimes ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
