// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: pb_lobby_vip.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb_lobby_vip";

export interface VipRuleItem {
  level: number;
  levelupExp: number;
  levelupGift: number;
  weekGift: number;
  monthGift: number;
  signToneup: number;
  isTransferSpeed: number;
  isService: number;
  weekMinCharge: number;
  monthMinCharge: number;
}

export interface scVipRules {
  items: VipRuleItem[];
}

export interface scVipStatus {
  level: number;
  curExp: number;
  needExp: number;
  weekCharge: number;
  monthCharge: number;
}

export interface csGetGift {
  type: number;
}

export interface scGetResult {
  code: number;
}

function createBaseVipRuleItem(): VipRuleItem {
  return {
    level: 0,
    levelupExp: 0,
    levelupGift: 0,
    weekGift: 0,
    monthGift: 0,
    signToneup: 0,
    isTransferSpeed: 0,
    isService: 0,
    weekMinCharge: 0,
    monthMinCharge: 0,
  };
}

export const VipRuleItem: MessageFns<VipRuleItem> = {
  encode(message: VipRuleItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.level !== 0) {
      writer.uint32(8).int32(message.level);
    }
    if (message.levelupExp !== 0) {
      writer.uint32(16).int64(message.levelupExp);
    }
    if (message.levelupGift !== 0) {
      writer.uint32(24).int64(message.levelupGift);
    }
    if (message.weekGift !== 0) {
      writer.uint32(32).int64(message.weekGift);
    }
    if (message.monthGift !== 0) {
      writer.uint32(40).int64(message.monthGift);
    }
    if (message.signToneup !== 0) {
      writer.uint32(48).int32(message.signToneup);
    }
    if (message.isTransferSpeed !== 0) {
      writer.uint32(56).int32(message.isTransferSpeed);
    }
    if (message.isService !== 0) {
      writer.uint32(64).int32(message.isService);
    }
    if (message.weekMinCharge !== 0) {
      writer.uint32(72).int64(message.weekMinCharge);
    }
    if (message.monthMinCharge !== 0) {
      writer.uint32(80).int64(message.monthMinCharge);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VipRuleItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVipRuleItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.levelupExp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.levelupGift = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.weekGift = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.monthGift = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.signToneup = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isTransferSpeed = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isService = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.weekMinCharge = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.monthMinCharge = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VipRuleItem {
    return {
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      levelupExp: isSet(object.levelupExp) ? globalThis.Number(object.levelupExp) : 0,
      levelupGift: isSet(object.levelupGift) ? globalThis.Number(object.levelupGift) : 0,
      weekGift: isSet(object.weekGift) ? globalThis.Number(object.weekGift) : 0,
      monthGift: isSet(object.monthGift) ? globalThis.Number(object.monthGift) : 0,
      signToneup: isSet(object.signToneup) ? globalThis.Number(object.signToneup) : 0,
      isTransferSpeed: isSet(object.isTransferSpeed) ? globalThis.Number(object.isTransferSpeed) : 0,
      isService: isSet(object.isService) ? globalThis.Number(object.isService) : 0,
      weekMinCharge: isSet(object.weekMinCharge) ? globalThis.Number(object.weekMinCharge) : 0,
      monthMinCharge: isSet(object.monthMinCharge) ? globalThis.Number(object.monthMinCharge) : 0,
    };
  },

  toJSON(message: VipRuleItem): unknown {
    const obj: any = {};
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.levelupExp !== 0) {
      obj.levelupExp = Math.round(message.levelupExp);
    }
    if (message.levelupGift !== 0) {
      obj.levelupGift = Math.round(message.levelupGift);
    }
    if (message.weekGift !== 0) {
      obj.weekGift = Math.round(message.weekGift);
    }
    if (message.monthGift !== 0) {
      obj.monthGift = Math.round(message.monthGift);
    }
    if (message.signToneup !== 0) {
      obj.signToneup = Math.round(message.signToneup);
    }
    if (message.isTransferSpeed !== 0) {
      obj.isTransferSpeed = Math.round(message.isTransferSpeed);
    }
    if (message.isService !== 0) {
      obj.isService = Math.round(message.isService);
    }
    if (message.weekMinCharge !== 0) {
      obj.weekMinCharge = Math.round(message.weekMinCharge);
    }
    if (message.monthMinCharge !== 0) {
      obj.monthMinCharge = Math.round(message.monthMinCharge);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VipRuleItem>, I>>(base?: I): VipRuleItem {
    return VipRuleItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VipRuleItem>, I>>(object: I): VipRuleItem {
    const message = createBaseVipRuleItem();
    message.level = object.level ?? 0;
    message.levelupExp = object.levelupExp ?? 0;
    message.levelupGift = object.levelupGift ?? 0;
    message.weekGift = object.weekGift ?? 0;
    message.monthGift = object.monthGift ?? 0;
    message.signToneup = object.signToneup ?? 0;
    message.isTransferSpeed = object.isTransferSpeed ?? 0;
    message.isService = object.isService ?? 0;
    message.weekMinCharge = object.weekMinCharge ?? 0;
    message.monthMinCharge = object.monthMinCharge ?? 0;
    return message;
  },
};

function createBasescVipRules(): scVipRules {
  return { items: [] };
}

export const scVipRules: MessageFns<scVipRules> = {
  encode(message: scVipRules, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      VipRuleItem.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scVipRules {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescVipRules();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(VipRuleItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scVipRules {
    return {
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => VipRuleItem.fromJSON(e)) : [],
    };
  },

  toJSON(message: scVipRules): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => VipRuleItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scVipRules>, I>>(base?: I): scVipRules {
    return scVipRules.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scVipRules>, I>>(object: I): scVipRules {
    const message = createBasescVipRules();
    message.items = object.items?.map((e) => VipRuleItem.fromPartial(e)) || [];
    return message;
  },
};

function createBasescVipStatus(): scVipStatus {
  return { level: 0, curExp: 0, needExp: 0, weekCharge: 0, monthCharge: 0 };
}

export const scVipStatus: MessageFns<scVipStatus> = {
  encode(message: scVipStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.level !== 0) {
      writer.uint32(8).int32(message.level);
    }
    if (message.curExp !== 0) {
      writer.uint32(16).int64(message.curExp);
    }
    if (message.needExp !== 0) {
      writer.uint32(24).int64(message.needExp);
    }
    if (message.weekCharge !== 0) {
      writer.uint32(32).int64(message.weekCharge);
    }
    if (message.monthCharge !== 0) {
      writer.uint32(40).int64(message.monthCharge);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scVipStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescVipStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.curExp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.needExp = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.weekCharge = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.monthCharge = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scVipStatus {
    return {
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      curExp: isSet(object.curExp) ? globalThis.Number(object.curExp) : 0,
      needExp: isSet(object.needExp) ? globalThis.Number(object.needExp) : 0,
      weekCharge: isSet(object.weekCharge) ? globalThis.Number(object.weekCharge) : 0,
      monthCharge: isSet(object.monthCharge) ? globalThis.Number(object.monthCharge) : 0,
    };
  },

  toJSON(message: scVipStatus): unknown {
    const obj: any = {};
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.curExp !== 0) {
      obj.curExp = Math.round(message.curExp);
    }
    if (message.needExp !== 0) {
      obj.needExp = Math.round(message.needExp);
    }
    if (message.weekCharge !== 0) {
      obj.weekCharge = Math.round(message.weekCharge);
    }
    if (message.monthCharge !== 0) {
      obj.monthCharge = Math.round(message.monthCharge);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scVipStatus>, I>>(base?: I): scVipStatus {
    return scVipStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scVipStatus>, I>>(object: I): scVipStatus {
    const message = createBasescVipStatus();
    message.level = object.level ?? 0;
    message.curExp = object.curExp ?? 0;
    message.needExp = object.needExp ?? 0;
    message.weekCharge = object.weekCharge ?? 0;
    message.monthCharge = object.monthCharge ?? 0;
    return message;
  },
};

function createBasecsGetGift(): csGetGift {
  return { type: 0 };
}

export const csGetGift: MessageFns<csGetGift> = {
  encode(message: csGetGift, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csGetGift {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsGetGift();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csGetGift {
    return { type: isSet(object.type) ? globalThis.Number(object.type) : 0 };
  },

  toJSON(message: csGetGift): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csGetGift>, I>>(base?: I): csGetGift {
    return csGetGift.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csGetGift>, I>>(object: I): csGetGift {
    const message = createBasecsGetGift();
    message.type = object.type ?? 0;
    return message;
  },
};

function createBasescGetResult(): scGetResult {
  return { code: 0 };
}

export const scGetResult: MessageFns<scGetResult> = {
  encode(message: scGetResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scGetResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescGetResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scGetResult {
    return { code: isSet(object.code) ? globalThis.Number(object.code) : 0 };
  },

  toJSON(message: scGetResult): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scGetResult>, I>>(base?: I): scGetResult {
    return scGetResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scGetResult>, I>>(object: I): scGetResult {
    const message = createBasescGetResult();
    message.code = object.code ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
