// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: pb_lobby_stagedrechagre.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb_lobby_stagedrechagre";

export interface acceptPacketData {
  begintime: number;
  endtime: number;
  hitbet: number;
  deposit: number;
}

export interface packetData {
  type: number;
  status: number;
  cash: number;
  receivedmoney: number;
  acceptdata: acceptPacketData | undefined;
  min: number;
  max: number;
}

export interface scShowbeforeMsg {
  data: packetData[];
  continueday: number;
  betx: number;
}

export interface csStagedrechagreGet {
  id: number;
}

export interface scStagedrechagreGet {
  id: number;
}

function createBaseacceptPacketData(): acceptPacketData {
  return { begintime: 0, endtime: 0, hitbet: 0, deposit: 0 };
}

export const acceptPacketData: MessageFns<acceptPacketData> = {
  encode(message: acceptPacketData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.begintime !== 0) {
      writer.uint32(8).int64(message.begintime);
    }
    if (message.endtime !== 0) {
      writer.uint32(16).int64(message.endtime);
    }
    if (message.hitbet !== 0) {
      writer.uint32(24).int64(message.hitbet);
    }
    if (message.deposit !== 0) {
      writer.uint32(32).int64(message.deposit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): acceptPacketData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseacceptPacketData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.begintime = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.endtime = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.hitbet = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.deposit = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): acceptPacketData {
    return {
      begintime: isSet(object.begintime) ? globalThis.Number(object.begintime) : 0,
      endtime: isSet(object.endtime) ? globalThis.Number(object.endtime) : 0,
      hitbet: isSet(object.hitbet) ? globalThis.Number(object.hitbet) : 0,
      deposit: isSet(object.deposit) ? globalThis.Number(object.deposit) : 0,
    };
  },

  toJSON(message: acceptPacketData): unknown {
    const obj: any = {};
    if (message.begintime !== 0) {
      obj.begintime = Math.round(message.begintime);
    }
    if (message.endtime !== 0) {
      obj.endtime = Math.round(message.endtime);
    }
    if (message.hitbet !== 0) {
      obj.hitbet = Math.round(message.hitbet);
    }
    if (message.deposit !== 0) {
      obj.deposit = Math.round(message.deposit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<acceptPacketData>, I>>(base?: I): acceptPacketData {
    return acceptPacketData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<acceptPacketData>, I>>(object: I): acceptPacketData {
    const message = createBaseacceptPacketData();
    message.begintime = object.begintime ?? 0;
    message.endtime = object.endtime ?? 0;
    message.hitbet = object.hitbet ?? 0;
    message.deposit = object.deposit ?? 0;
    return message;
  },
};

function createBasepacketData(): packetData {
  return { type: 0, status: 0, cash: 0, receivedmoney: 0, acceptdata: undefined, min: 0, max: 0 };
}

export const packetData: MessageFns<packetData> = {
  encode(message: packetData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    if (message.cash !== 0) {
      writer.uint32(24).int32(message.cash);
    }
    if (message.receivedmoney !== 0) {
      writer.uint32(32).int64(message.receivedmoney);
    }
    if (message.acceptdata !== undefined) {
      acceptPacketData.encode(message.acceptdata, writer.uint32(42).fork()).join();
    }
    if (message.min !== 0) {
      writer.uint32(48).int64(message.min);
    }
    if (message.max !== 0) {
      writer.uint32(56).int64(message.max);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): packetData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasepacketData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.cash = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.receivedmoney = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.acceptdata = acceptPacketData.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.min = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.max = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): packetData {
    return {
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      cash: isSet(object.cash) ? globalThis.Number(object.cash) : 0,
      receivedmoney: isSet(object.receivedmoney) ? globalThis.Number(object.receivedmoney) : 0,
      acceptdata: isSet(object.acceptdata) ? acceptPacketData.fromJSON(object.acceptdata) : undefined,
      min: isSet(object.min) ? globalThis.Number(object.min) : 0,
      max: isSet(object.max) ? globalThis.Number(object.max) : 0,
    };
  },

  toJSON(message: packetData): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.cash !== 0) {
      obj.cash = Math.round(message.cash);
    }
    if (message.receivedmoney !== 0) {
      obj.receivedmoney = Math.round(message.receivedmoney);
    }
    if (message.acceptdata !== undefined) {
      obj.acceptdata = acceptPacketData.toJSON(message.acceptdata);
    }
    if (message.min !== 0) {
      obj.min = Math.round(message.min);
    }
    if (message.max !== 0) {
      obj.max = Math.round(message.max);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<packetData>, I>>(base?: I): packetData {
    return packetData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<packetData>, I>>(object: I): packetData {
    const message = createBasepacketData();
    message.type = object.type ?? 0;
    message.status = object.status ?? 0;
    message.cash = object.cash ?? 0;
    message.receivedmoney = object.receivedmoney ?? 0;
    message.acceptdata = (object.acceptdata !== undefined && object.acceptdata !== null)
      ? acceptPacketData.fromPartial(object.acceptdata)
      : undefined;
    message.min = object.min ?? 0;
    message.max = object.max ?? 0;
    return message;
  },
};

function createBasescShowbeforeMsg(): scShowbeforeMsg {
  return { data: [], continueday: 0, betx: 0 };
}

export const scShowbeforeMsg: MessageFns<scShowbeforeMsg> = {
  encode(message: scShowbeforeMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      packetData.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.continueday !== 0) {
      writer.uint32(16).int32(message.continueday);
    }
    if (message.betx !== 0) {
      writer.uint32(24).int32(message.betx);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scShowbeforeMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescShowbeforeMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(packetData.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.continueday = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.betx = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scShowbeforeMsg {
    return {
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => packetData.fromJSON(e)) : [],
      continueday: isSet(object.continueday) ? globalThis.Number(object.continueday) : 0,
      betx: isSet(object.betx) ? globalThis.Number(object.betx) : 0,
    };
  },

  toJSON(message: scShowbeforeMsg): unknown {
    const obj: any = {};
    if (message.data?.length) {
      obj.data = message.data.map((e) => packetData.toJSON(e));
    }
    if (message.continueday !== 0) {
      obj.continueday = Math.round(message.continueday);
    }
    if (message.betx !== 0) {
      obj.betx = Math.round(message.betx);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scShowbeforeMsg>, I>>(base?: I): scShowbeforeMsg {
    return scShowbeforeMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scShowbeforeMsg>, I>>(object: I): scShowbeforeMsg {
    const message = createBasescShowbeforeMsg();
    message.data = object.data?.map((e) => packetData.fromPartial(e)) || [];
    message.continueday = object.continueday ?? 0;
    message.betx = object.betx ?? 0;
    return message;
  },
};

function createBasecsStagedrechagreGet(): csStagedrechagreGet {
  return { id: 0 };
}

export const csStagedrechagreGet: MessageFns<csStagedrechagreGet> = {
  encode(message: csStagedrechagreGet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csStagedrechagreGet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsStagedrechagreGet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csStagedrechagreGet {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: csStagedrechagreGet): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csStagedrechagreGet>, I>>(base?: I): csStagedrechagreGet {
    return csStagedrechagreGet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csStagedrechagreGet>, I>>(object: I): csStagedrechagreGet {
    const message = createBasecsStagedrechagreGet();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBasescStagedrechagreGet(): scStagedrechagreGet {
  return { id: 0 };
}

export const scStagedrechagreGet: MessageFns<scStagedrechagreGet> = {
  encode(message: scStagedrechagreGet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scStagedrechagreGet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescStagedrechagreGet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scStagedrechagreGet {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: scStagedrechagreGet): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scStagedrechagreGet>, I>>(base?: I): scStagedrechagreGet {
    return scStagedrechagreGet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scStagedrechagreGet>, I>>(object: I): scStagedrechagreGet {
    const message = createBasescStagedrechagreGet();
    message.id = object.id ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
