// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: pb_lobby_mail.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb_lobby_mail";

export interface lobbyMailProp {
  propID: number;
  propCount: number;
}

export interface lobbyMailMsg {
  mailid: number;
  title: string;
  timestamp: number;
  bOpen: boolean;
  sender: string;
  type: number;
  bGet: boolean;
  content: string;
}

export interface lobbyMailListMsg {
  mailList: lobbyMailMsg[];
}

export interface csMailOpen {
  mailid: number;
}

export interface scMailOpen {
  mailid: number;
  content: string;
  timestamp: number;
  prop: lobbyMailProp[];
  type: number;
}

export interface csMailDelete {
  mailid: number;
}

export interface scMailDelete {
  mailid: number;
}

export interface csMailGetprop {
  mailid: number;
}

export interface scMailGetprop {
  mailid: number;
  status: number;
  prop: lobbyMailProp[];
  curUserScore: number[];
}

export interface csMailSysmailid {
}

export interface scMailSysmailid {
  mailid: number[];
}

function createBaselobbyMailProp(): lobbyMailProp {
  return { propID: 0, propCount: 0 };
}

export const lobbyMailProp: MessageFns<lobbyMailProp> = {
  encode(message: lobbyMailProp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.propID !== 0) {
      writer.uint32(8).int32(message.propID);
    }
    if (message.propCount !== 0) {
      writer.uint32(16).int64(message.propCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): lobbyMailProp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaselobbyMailProp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.propID = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.propCount = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): lobbyMailProp {
    return {
      propID: isSet(object.propID) ? globalThis.Number(object.propID) : 0,
      propCount: isSet(object.propCount) ? globalThis.Number(object.propCount) : 0,
    };
  },

  toJSON(message: lobbyMailProp): unknown {
    const obj: any = {};
    if (message.propID !== 0) {
      obj.propID = Math.round(message.propID);
    }
    if (message.propCount !== 0) {
      obj.propCount = Math.round(message.propCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<lobbyMailProp>, I>>(base?: I): lobbyMailProp {
    return lobbyMailProp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<lobbyMailProp>, I>>(object: I): lobbyMailProp {
    const message = createBaselobbyMailProp();
    message.propID = object.propID ?? 0;
    message.propCount = object.propCount ?? 0;
    return message;
  },
};

function createBaselobbyMailMsg(): lobbyMailMsg {
  return { mailid: 0, title: "", timestamp: 0, bOpen: false, sender: "", type: 0, bGet: false, content: "" };
}

export const lobbyMailMsg: MessageFns<lobbyMailMsg> = {
  encode(message: lobbyMailMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mailid !== 0) {
      writer.uint32(8).int64(message.mailid);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.timestamp !== 0) {
      writer.uint32(24).int64(message.timestamp);
    }
    if (message.bOpen !== false) {
      writer.uint32(32).bool(message.bOpen);
    }
    if (message.sender !== "") {
      writer.uint32(42).string(message.sender);
    }
    if (message.type !== 0) {
      writer.uint32(48).int32(message.type);
    }
    if (message.bGet !== false) {
      writer.uint32(56).bool(message.bGet);
    }
    if (message.content !== "") {
      writer.uint32(66).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): lobbyMailMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaselobbyMailMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mailid = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.bOpen = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sender = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.bGet = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): lobbyMailMsg {
    return {
      mailid: isSet(object.mailid) ? globalThis.Number(object.mailid) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      bOpen: isSet(object.bOpen) ? globalThis.Boolean(object.bOpen) : false,
      sender: isSet(object.sender) ? globalThis.String(object.sender) : "",
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      bGet: isSet(object.bGet) ? globalThis.Boolean(object.bGet) : false,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
    };
  },

  toJSON(message: lobbyMailMsg): unknown {
    const obj: any = {};
    if (message.mailid !== 0) {
      obj.mailid = Math.round(message.mailid);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.bOpen !== false) {
      obj.bOpen = message.bOpen;
    }
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.bGet !== false) {
      obj.bGet = message.bGet;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<lobbyMailMsg>, I>>(base?: I): lobbyMailMsg {
    return lobbyMailMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<lobbyMailMsg>, I>>(object: I): lobbyMailMsg {
    const message = createBaselobbyMailMsg();
    message.mailid = object.mailid ?? 0;
    message.title = object.title ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.bOpen = object.bOpen ?? false;
    message.sender = object.sender ?? "";
    message.type = object.type ?? 0;
    message.bGet = object.bGet ?? false;
    message.content = object.content ?? "";
    return message;
  },
};

function createBaselobbyMailListMsg(): lobbyMailListMsg {
  return { mailList: [] };
}

export const lobbyMailListMsg: MessageFns<lobbyMailListMsg> = {
  encode(message: lobbyMailListMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.mailList) {
      lobbyMailMsg.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): lobbyMailListMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaselobbyMailListMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.mailList.push(lobbyMailMsg.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): lobbyMailListMsg {
    return {
      mailList: globalThis.Array.isArray(object?.mailList)
        ? object.mailList.map((e: any) => lobbyMailMsg.fromJSON(e))
        : [],
    };
  },

  toJSON(message: lobbyMailListMsg): unknown {
    const obj: any = {};
    if (message.mailList?.length) {
      obj.mailList = message.mailList.map((e) => lobbyMailMsg.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<lobbyMailListMsg>, I>>(base?: I): lobbyMailListMsg {
    return lobbyMailListMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<lobbyMailListMsg>, I>>(object: I): lobbyMailListMsg {
    const message = createBaselobbyMailListMsg();
    message.mailList = object.mailList?.map((e) => lobbyMailMsg.fromPartial(e)) || [];
    return message;
  },
};

function createBasecsMailOpen(): csMailOpen {
  return { mailid: 0 };
}

export const csMailOpen: MessageFns<csMailOpen> = {
  encode(message: csMailOpen, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mailid !== 0) {
      writer.uint32(8).int64(message.mailid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csMailOpen {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsMailOpen();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mailid = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csMailOpen {
    return { mailid: isSet(object.mailid) ? globalThis.Number(object.mailid) : 0 };
  },

  toJSON(message: csMailOpen): unknown {
    const obj: any = {};
    if (message.mailid !== 0) {
      obj.mailid = Math.round(message.mailid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csMailOpen>, I>>(base?: I): csMailOpen {
    return csMailOpen.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csMailOpen>, I>>(object: I): csMailOpen {
    const message = createBasecsMailOpen();
    message.mailid = object.mailid ?? 0;
    return message;
  },
};

function createBasescMailOpen(): scMailOpen {
  return { mailid: 0, content: "", timestamp: 0, prop: [], type: 0 };
}

export const scMailOpen: MessageFns<scMailOpen> = {
  encode(message: scMailOpen, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mailid !== 0) {
      writer.uint32(8).int64(message.mailid);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    if (message.timestamp !== 0) {
      writer.uint32(24).int64(message.timestamp);
    }
    for (const v of message.prop) {
      lobbyMailProp.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.type !== 0) {
      writer.uint32(40).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scMailOpen {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescMailOpen();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mailid = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.prop.push(lobbyMailProp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scMailOpen {
    return {
      mailid: isSet(object.mailid) ? globalThis.Number(object.mailid) : 0,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      prop: globalThis.Array.isArray(object?.prop) ? object.prop.map((e: any) => lobbyMailProp.fromJSON(e)) : [],
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
    };
  },

  toJSON(message: scMailOpen): unknown {
    const obj: any = {};
    if (message.mailid !== 0) {
      obj.mailid = Math.round(message.mailid);
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.prop?.length) {
      obj.prop = message.prop.map((e) => lobbyMailProp.toJSON(e));
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scMailOpen>, I>>(base?: I): scMailOpen {
    return scMailOpen.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scMailOpen>, I>>(object: I): scMailOpen {
    const message = createBasescMailOpen();
    message.mailid = object.mailid ?? 0;
    message.content = object.content ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.prop = object.prop?.map((e) => lobbyMailProp.fromPartial(e)) || [];
    message.type = object.type ?? 0;
    return message;
  },
};

function createBasecsMailDelete(): csMailDelete {
  return { mailid: 0 };
}

export const csMailDelete: MessageFns<csMailDelete> = {
  encode(message: csMailDelete, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mailid !== 0) {
      writer.uint32(8).int64(message.mailid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csMailDelete {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsMailDelete();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mailid = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csMailDelete {
    return { mailid: isSet(object.mailid) ? globalThis.Number(object.mailid) : 0 };
  },

  toJSON(message: csMailDelete): unknown {
    const obj: any = {};
    if (message.mailid !== 0) {
      obj.mailid = Math.round(message.mailid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csMailDelete>, I>>(base?: I): csMailDelete {
    return csMailDelete.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csMailDelete>, I>>(object: I): csMailDelete {
    const message = createBasecsMailDelete();
    message.mailid = object.mailid ?? 0;
    return message;
  },
};

function createBasescMailDelete(): scMailDelete {
  return { mailid: 0 };
}

export const scMailDelete: MessageFns<scMailDelete> = {
  encode(message: scMailDelete, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mailid !== 0) {
      writer.uint32(8).int64(message.mailid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scMailDelete {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescMailDelete();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mailid = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scMailDelete {
    return { mailid: isSet(object.mailid) ? globalThis.Number(object.mailid) : 0 };
  },

  toJSON(message: scMailDelete): unknown {
    const obj: any = {};
    if (message.mailid !== 0) {
      obj.mailid = Math.round(message.mailid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scMailDelete>, I>>(base?: I): scMailDelete {
    return scMailDelete.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scMailDelete>, I>>(object: I): scMailDelete {
    const message = createBasescMailDelete();
    message.mailid = object.mailid ?? 0;
    return message;
  },
};

function createBasecsMailGetprop(): csMailGetprop {
  return { mailid: 0 };
}

export const csMailGetprop: MessageFns<csMailGetprop> = {
  encode(message: csMailGetprop, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mailid !== 0) {
      writer.uint32(8).int64(message.mailid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csMailGetprop {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsMailGetprop();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mailid = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csMailGetprop {
    return { mailid: isSet(object.mailid) ? globalThis.Number(object.mailid) : 0 };
  },

  toJSON(message: csMailGetprop): unknown {
    const obj: any = {};
    if (message.mailid !== 0) {
      obj.mailid = Math.round(message.mailid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csMailGetprop>, I>>(base?: I): csMailGetprop {
    return csMailGetprop.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csMailGetprop>, I>>(object: I): csMailGetprop {
    const message = createBasecsMailGetprop();
    message.mailid = object.mailid ?? 0;
    return message;
  },
};

function createBasescMailGetprop(): scMailGetprop {
  return { mailid: 0, status: 0, prop: [], curUserScore: [] };
}

export const scMailGetprop: MessageFns<scMailGetprop> = {
  encode(message: scMailGetprop, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mailid !== 0) {
      writer.uint32(8).int64(message.mailid);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    for (const v of message.prop) {
      lobbyMailProp.encode(v!, writer.uint32(26).fork()).join();
    }
    writer.uint32(34).fork();
    for (const v of message.curUserScore) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scMailGetprop {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescMailGetprop();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mailid = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.prop.push(lobbyMailProp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.curUserScore.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.curUserScore.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scMailGetprop {
    return {
      mailid: isSet(object.mailid) ? globalThis.Number(object.mailid) : 0,
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      prop: globalThis.Array.isArray(object?.prop) ? object.prop.map((e: any) => lobbyMailProp.fromJSON(e)) : [],
      curUserScore: globalThis.Array.isArray(object?.curUserScore)
        ? object.curUserScore.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: scMailGetprop): unknown {
    const obj: any = {};
    if (message.mailid !== 0) {
      obj.mailid = Math.round(message.mailid);
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.prop?.length) {
      obj.prop = message.prop.map((e) => lobbyMailProp.toJSON(e));
    }
    if (message.curUserScore?.length) {
      obj.curUserScore = message.curUserScore.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scMailGetprop>, I>>(base?: I): scMailGetprop {
    return scMailGetprop.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scMailGetprop>, I>>(object: I): scMailGetprop {
    const message = createBasescMailGetprop();
    message.mailid = object.mailid ?? 0;
    message.status = object.status ?? 0;
    message.prop = object.prop?.map((e) => lobbyMailProp.fromPartial(e)) || [];
    message.curUserScore = object.curUserScore?.map((e) => e) || [];
    return message;
  },
};

function createBasecsMailSysmailid(): csMailSysmailid {
  return {};
}

export const csMailSysmailid: MessageFns<csMailSysmailid> = {
  encode(_: csMailSysmailid, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csMailSysmailid {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsMailSysmailid();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): csMailSysmailid {
    return {};
  },

  toJSON(_: csMailSysmailid): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<csMailSysmailid>, I>>(base?: I): csMailSysmailid {
    return csMailSysmailid.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csMailSysmailid>, I>>(_: I): csMailSysmailid {
    const message = createBasecsMailSysmailid();
    return message;
  },
};

function createBasescMailSysmailid(): scMailSysmailid {
  return { mailid: [] };
}

export const scMailSysmailid: MessageFns<scMailSysmailid> = {
  encode(message: scMailSysmailid, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.mailid) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scMailSysmailid {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescMailSysmailid();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.mailid.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.mailid.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scMailSysmailid {
    return {
      mailid: globalThis.Array.isArray(object?.mailid) ? object.mailid.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: scMailSysmailid): unknown {
    const obj: any = {};
    if (message.mailid?.length) {
      obj.mailid = message.mailid.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scMailSysmailid>, I>>(base?: I): scMailSysmailid {
    return scMailSysmailid.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scMailSysmailid>, I>>(object: I): scMailSysmailid {
    const message = createBasescMailSysmailid();
    message.mailid = object.mailid?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
