// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: pb_lobby.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb_lobby";

export interface scShowbeforeMsg {
  begintime: number;
  starttime: number;
  endtime: number;
  status: number;
  money: number;
}

export interface scRotaMsg {
  result: number;
  rotaCount: number;
}

export interface scMyRecodeMsg {
  records: number[];
}

export interface scGetAllMoneyMsg {
  total: number;
  received: number;
}

export interface scNewHelpMsg {
  hasNew: boolean;
}

export interface scGetMyMoneyRecodeMsg {
  records: number[];
}

export interface scGetSharephone {
  phone: string;
}

export interface csMyRecodeMsg {
  uid: number;
}

export interface csGetMyMoneyRecodeMsg {
  uid: number;
}

function createBasescShowbeforeMsg(): scShowbeforeMsg {
  return { begintime: 0, starttime: 0, endtime: 0, status: 0, money: 0 };
}

export const scShowbeforeMsg: MessageFns<scShowbeforeMsg> = {
  encode(message: scShowbeforeMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.begintime !== 0) {
      writer.uint32(8).int64(message.begintime);
    }
    if (message.starttime !== 0) {
      writer.uint32(16).int64(message.starttime);
    }
    if (message.endtime !== 0) {
      writer.uint32(24).int64(message.endtime);
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    if (message.money !== 0) {
      writer.uint32(40).int64(message.money);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scShowbeforeMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescShowbeforeMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.begintime = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.starttime = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.endtime = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.money = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scShowbeforeMsg {
    return {
      begintime: isSet(object.begintime) ? globalThis.Number(object.begintime) : 0,
      starttime: isSet(object.starttime) ? globalThis.Number(object.starttime) : 0,
      endtime: isSet(object.endtime) ? globalThis.Number(object.endtime) : 0,
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      money: isSet(object.money) ? globalThis.Number(object.money) : 0,
    };
  },

  toJSON(message: scShowbeforeMsg): unknown {
    const obj: any = {};
    if (message.begintime !== 0) {
      obj.begintime = Math.round(message.begintime);
    }
    if (message.starttime !== 0) {
      obj.starttime = Math.round(message.starttime);
    }
    if (message.endtime !== 0) {
      obj.endtime = Math.round(message.endtime);
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.money !== 0) {
      obj.money = Math.round(message.money);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scShowbeforeMsg>, I>>(base?: I): scShowbeforeMsg {
    return scShowbeforeMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scShowbeforeMsg>, I>>(object: I): scShowbeforeMsg {
    const message = createBasescShowbeforeMsg();
    message.begintime = object.begintime ?? 0;
    message.starttime = object.starttime ?? 0;
    message.endtime = object.endtime ?? 0;
    message.status = object.status ?? 0;
    message.money = object.money ?? 0;
    return message;
  },
};

function createBasescRotaMsg(): scRotaMsg {
  return { result: 0, rotaCount: 0 };
}

export const scRotaMsg: MessageFns<scRotaMsg> = {
  encode(message: scRotaMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.result !== 0) {
      writer.uint32(8).int64(message.result);
    }
    if (message.rotaCount !== 0) {
      writer.uint32(16).int32(message.rotaCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scRotaMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescRotaMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.result = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.rotaCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scRotaMsg {
    return {
      result: isSet(object.result) ? globalThis.Number(object.result) : 0,
      rotaCount: isSet(object.rotaCount) ? globalThis.Number(object.rotaCount) : 0,
    };
  },

  toJSON(message: scRotaMsg): unknown {
    const obj: any = {};
    if (message.result !== 0) {
      obj.result = Math.round(message.result);
    }
    if (message.rotaCount !== 0) {
      obj.rotaCount = Math.round(message.rotaCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scRotaMsg>, I>>(base?: I): scRotaMsg {
    return scRotaMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scRotaMsg>, I>>(object: I): scRotaMsg {
    const message = createBasescRotaMsg();
    message.result = object.result ?? 0;
    message.rotaCount = object.rotaCount ?? 0;
    return message;
  },
};

function createBasescMyRecodeMsg(): scMyRecodeMsg {
  return { records: [] };
}

export const scMyRecodeMsg: MessageFns<scMyRecodeMsg> = {
  encode(message: scMyRecodeMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.records) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scMyRecodeMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescMyRecodeMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.records.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.records.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scMyRecodeMsg {
    return {
      records: globalThis.Array.isArray(object?.records) ? object.records.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: scMyRecodeMsg): unknown {
    const obj: any = {};
    if (message.records?.length) {
      obj.records = message.records.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scMyRecodeMsg>, I>>(base?: I): scMyRecodeMsg {
    return scMyRecodeMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scMyRecodeMsg>, I>>(object: I): scMyRecodeMsg {
    const message = createBasescMyRecodeMsg();
    message.records = object.records?.map((e) => e) || [];
    return message;
  },
};

function createBasescGetAllMoneyMsg(): scGetAllMoneyMsg {
  return { total: 0, received: 0 };
}

export const scGetAllMoneyMsg: MessageFns<scGetAllMoneyMsg> = {
  encode(message: scGetAllMoneyMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.total !== 0) {
      writer.uint32(8).int64(message.total);
    }
    if (message.received !== 0) {
      writer.uint32(16).int64(message.received);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scGetAllMoneyMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescGetAllMoneyMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.total = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.received = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scGetAllMoneyMsg {
    return {
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
      received: isSet(object.received) ? globalThis.Number(object.received) : 0,
    };
  },

  toJSON(message: scGetAllMoneyMsg): unknown {
    const obj: any = {};
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    if (message.received !== 0) {
      obj.received = Math.round(message.received);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scGetAllMoneyMsg>, I>>(base?: I): scGetAllMoneyMsg {
    return scGetAllMoneyMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scGetAllMoneyMsg>, I>>(object: I): scGetAllMoneyMsg {
    const message = createBasescGetAllMoneyMsg();
    message.total = object.total ?? 0;
    message.received = object.received ?? 0;
    return message;
  },
};

function createBasescNewHelpMsg(): scNewHelpMsg {
  return { hasNew: false };
}

export const scNewHelpMsg: MessageFns<scNewHelpMsg> = {
  encode(message: scNewHelpMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hasNew !== false) {
      writer.uint32(8).bool(message.hasNew);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scNewHelpMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescNewHelpMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.hasNew = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scNewHelpMsg {
    return { hasNew: isSet(object.hasNew) ? globalThis.Boolean(object.hasNew) : false };
  },

  toJSON(message: scNewHelpMsg): unknown {
    const obj: any = {};
    if (message.hasNew !== false) {
      obj.hasNew = message.hasNew;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scNewHelpMsg>, I>>(base?: I): scNewHelpMsg {
    return scNewHelpMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scNewHelpMsg>, I>>(object: I): scNewHelpMsg {
    const message = createBasescNewHelpMsg();
    message.hasNew = object.hasNew ?? false;
    return message;
  },
};

function createBasescGetMyMoneyRecodeMsg(): scGetMyMoneyRecodeMsg {
  return { records: [] };
}

export const scGetMyMoneyRecodeMsg: MessageFns<scGetMyMoneyRecodeMsg> = {
  encode(message: scGetMyMoneyRecodeMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.records) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scGetMyMoneyRecodeMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescGetMyMoneyRecodeMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.records.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.records.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scGetMyMoneyRecodeMsg {
    return {
      records: globalThis.Array.isArray(object?.records) ? object.records.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: scGetMyMoneyRecodeMsg): unknown {
    const obj: any = {};
    if (message.records?.length) {
      obj.records = message.records.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scGetMyMoneyRecodeMsg>, I>>(base?: I): scGetMyMoneyRecodeMsg {
    return scGetMyMoneyRecodeMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scGetMyMoneyRecodeMsg>, I>>(object: I): scGetMyMoneyRecodeMsg {
    const message = createBasescGetMyMoneyRecodeMsg();
    message.records = object.records?.map((e) => e) || [];
    return message;
  },
};

function createBasescGetSharephone(): scGetSharephone {
  return { phone: "" };
}

export const scGetSharephone: MessageFns<scGetSharephone> = {
  encode(message: scGetSharephone, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.phone !== "") {
      writer.uint32(10).string(message.phone);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scGetSharephone {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescGetSharephone();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scGetSharephone {
    return { phone: isSet(object.phone) ? globalThis.String(object.phone) : "" };
  },

  toJSON(message: scGetSharephone): unknown {
    const obj: any = {};
    if (message.phone !== "") {
      obj.phone = message.phone;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scGetSharephone>, I>>(base?: I): scGetSharephone {
    return scGetSharephone.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scGetSharephone>, I>>(object: I): scGetSharephone {
    const message = createBasescGetSharephone();
    message.phone = object.phone ?? "";
    return message;
  },
};

function createBasecsMyRecodeMsg(): csMyRecodeMsg {
  return { uid: 0 };
}

export const csMyRecodeMsg: MessageFns<csMyRecodeMsg> = {
  encode(message: csMyRecodeMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== 0) {
      writer.uint32(8).int32(message.uid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csMyRecodeMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsMyRecodeMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.uid = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csMyRecodeMsg {
    return { uid: isSet(object.uid) ? globalThis.Number(object.uid) : 0 };
  },

  toJSON(message: csMyRecodeMsg): unknown {
    const obj: any = {};
    if (message.uid !== 0) {
      obj.uid = Math.round(message.uid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csMyRecodeMsg>, I>>(base?: I): csMyRecodeMsg {
    return csMyRecodeMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csMyRecodeMsg>, I>>(object: I): csMyRecodeMsg {
    const message = createBasecsMyRecodeMsg();
    message.uid = object.uid ?? 0;
    return message;
  },
};

function createBasecsGetMyMoneyRecodeMsg(): csGetMyMoneyRecodeMsg {
  return { uid: 0 };
}

export const csGetMyMoneyRecodeMsg: MessageFns<csGetMyMoneyRecodeMsg> = {
  encode(message: csGetMyMoneyRecodeMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== 0) {
      writer.uint32(8).int32(message.uid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csGetMyMoneyRecodeMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsGetMyMoneyRecodeMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.uid = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csGetMyMoneyRecodeMsg {
    return { uid: isSet(object.uid) ? globalThis.Number(object.uid) : 0 };
  },

  toJSON(message: csGetMyMoneyRecodeMsg): unknown {
    const obj: any = {};
    if (message.uid !== 0) {
      obj.uid = Math.round(message.uid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csGetMyMoneyRecodeMsg>, I>>(base?: I): csGetMyMoneyRecodeMsg {
    return csGetMyMoneyRecodeMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csGetMyMoneyRecodeMsg>, I>>(object: I): csGetMyMoneyRecodeMsg {
    const message = createBasecsGetMyMoneyRecodeMsg();
    message.uid = object.uid ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
