// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: pb_lobby_mall.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb_lobby_mall";

export interface csPayitemList {
}

export interface scPayitemList {
  list: payItem[];
}

export interface csPayItem {
  id: number;
}

export interface scPayItem {
  id: number;
  code: number;
  msg: string;
}

export interface payItem {
  id: number;
  originalGold: number;
  realGold: number;
  present: number;
  originalPrice: number;
  realPrice: number;
  type: number;
  flag: number;
  discount: number;
  startTimeStamp: number;
  durationTime: number;
  vip: number;
  sortid: number;
}

export interface notifyFalshSale {
  list: payItem[];
}

export interface csChargeForCoin {
  id: number;
}

export interface scChargeForCoin {
  code: number;
  msg: string;
}

export interface csChargeBuyCoin {
  id: number;
}

export interface scChargeBuyCoin {
  code: number;
  msg: string;
}

export interface csChargeHistroy {
  /** número de registros por página */
  number: number;
  /** número da página */
  page: number;
  day: number;
}

export interface scChargeHistroy {
  list: chargeRecord[];
}

export interface chargeRecord {
  /** número do pedido */
  orderNo: string;
  /** quantidade de moedas */
  coins: number;
  /** timestamp da criação */
  orderTime: number;
  /** valor pago */
  amount: number;
  /** estado da transação */
  state: number;
  /** URL de atendimento ao cliente */
  csUrl: string;
  /** URL de pagamento (opcional) */
  payUrl: string;
  /** ID do tipo de pagamento */
  typeId: number;
  /** nome do produto ou pacote */
  name: string;
}

export interface scGetFirstGift {
  result: number;
}

export interface scFirstGiftInfoMsg {
  giftID: number;
  giftDesc: string;
}

export interface scPayitemBaseInfoMsg {
  list: payItem[];
}

function createBasecsPayitemList(): csPayitemList {
  return {};
}

export const csPayitemList: MessageFns<csPayitemList> = {
  encode(_: csPayitemList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csPayitemList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsPayitemList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): csPayitemList {
    return {};
  },

  toJSON(_: csPayitemList): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<csPayitemList>, I>>(base?: I): csPayitemList {
    return csPayitemList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csPayitemList>, I>>(_: I): csPayitemList {
    const message = createBasecsPayitemList();
    return message;
  },
};

function createBasescPayitemList(): scPayitemList {
  return { list: [] };
}

export const scPayitemList: MessageFns<scPayitemList> = {
  encode(message: scPayitemList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.list) {
      payItem.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scPayitemList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescPayitemList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.list.push(payItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scPayitemList {
    return { list: globalThis.Array.isArray(object?.list) ? object.list.map((e: any) => payItem.fromJSON(e)) : [] };
  },

  toJSON(message: scPayitemList): unknown {
    const obj: any = {};
    if (message.list?.length) {
      obj.list = message.list.map((e) => payItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scPayitemList>, I>>(base?: I): scPayitemList {
    return scPayitemList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scPayitemList>, I>>(object: I): scPayitemList {
    const message = createBasescPayitemList();
    message.list = object.list?.map((e) => payItem.fromPartial(e)) || [];
    return message;
  },
};

function createBasecsPayItem(): csPayItem {
  return { id: 0 };
}

export const csPayItem: MessageFns<csPayItem> = {
  encode(message: csPayItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csPayItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsPayItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csPayItem {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: csPayItem): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csPayItem>, I>>(base?: I): csPayItem {
    return csPayItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csPayItem>, I>>(object: I): csPayItem {
    const message = createBasecsPayItem();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBasescPayItem(): scPayItem {
  return { id: 0, code: 0, msg: "" };
}

export const scPayItem: MessageFns<scPayItem> = {
  encode(message: scPayItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.msg !== "") {
      writer.uint32(26).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scPayItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescPayItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scPayItem {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: scPayItem): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scPayItem>, I>>(base?: I): scPayItem {
    return scPayItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scPayItem>, I>>(object: I): scPayItem {
    const message = createBasescPayItem();
    message.id = object.id ?? 0;
    message.code = object.code ?? 0;
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBasepayItem(): payItem {
  return {
    id: 0,
    originalGold: 0,
    realGold: 0,
    present: 0,
    originalPrice: 0,
    realPrice: 0,
    type: 0,
    flag: 0,
    discount: 0,
    startTimeStamp: 0,
    durationTime: 0,
    vip: 0,
    sortid: 0,
  };
}

export const payItem: MessageFns<payItem> = {
  encode(message: payItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.originalGold !== 0) {
      writer.uint32(16).int64(message.originalGold);
    }
    if (message.realGold !== 0) {
      writer.uint32(24).int64(message.realGold);
    }
    if (message.present !== 0) {
      writer.uint32(32).int32(message.present);
    }
    if (message.originalPrice !== 0) {
      writer.uint32(40).int64(message.originalPrice);
    }
    if (message.realPrice !== 0) {
      writer.uint32(48).int64(message.realPrice);
    }
    if (message.type !== 0) {
      writer.uint32(64).int32(message.type);
    }
    if (message.flag !== 0) {
      writer.uint32(72).int32(message.flag);
    }
    if (message.discount !== 0) {
      writer.uint32(80).int32(message.discount);
    }
    if (message.startTimeStamp !== 0) {
      writer.uint32(88).int32(message.startTimeStamp);
    }
    if (message.durationTime !== 0) {
      writer.uint32(96).int32(message.durationTime);
    }
    if (message.vip !== 0) {
      writer.uint32(104).int32(message.vip);
    }
    if (message.sortid !== 0) {
      writer.uint32(112).int32(message.sortid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): payItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasepayItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.originalGold = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.realGold = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.present = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.originalPrice = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.realPrice = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.flag = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.discount = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.startTimeStamp = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.durationTime = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.vip = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.sortid = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): payItem {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      originalGold: isSet(object.originalGold) ? globalThis.Number(object.originalGold) : 0,
      realGold: isSet(object.realGold) ? globalThis.Number(object.realGold) : 0,
      present: isSet(object.present) ? globalThis.Number(object.present) : 0,
      originalPrice: isSet(object.originalPrice) ? globalThis.Number(object.originalPrice) : 0,
      realPrice: isSet(object.realPrice) ? globalThis.Number(object.realPrice) : 0,
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      flag: isSet(object.flag) ? globalThis.Number(object.flag) : 0,
      discount: isSet(object.discount) ? globalThis.Number(object.discount) : 0,
      startTimeStamp: isSet(object.startTimeStamp) ? globalThis.Number(object.startTimeStamp) : 0,
      durationTime: isSet(object.durationTime) ? globalThis.Number(object.durationTime) : 0,
      vip: isSet(object.vip) ? globalThis.Number(object.vip) : 0,
      sortid: isSet(object.sortid) ? globalThis.Number(object.sortid) : 0,
    };
  },

  toJSON(message: payItem): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.originalGold !== 0) {
      obj.originalGold = Math.round(message.originalGold);
    }
    if (message.realGold !== 0) {
      obj.realGold = Math.round(message.realGold);
    }
    if (message.present !== 0) {
      obj.present = Math.round(message.present);
    }
    if (message.originalPrice !== 0) {
      obj.originalPrice = Math.round(message.originalPrice);
    }
    if (message.realPrice !== 0) {
      obj.realPrice = Math.round(message.realPrice);
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.flag !== 0) {
      obj.flag = Math.round(message.flag);
    }
    if (message.discount !== 0) {
      obj.discount = Math.round(message.discount);
    }
    if (message.startTimeStamp !== 0) {
      obj.startTimeStamp = Math.round(message.startTimeStamp);
    }
    if (message.durationTime !== 0) {
      obj.durationTime = Math.round(message.durationTime);
    }
    if (message.vip !== 0) {
      obj.vip = Math.round(message.vip);
    }
    if (message.sortid !== 0) {
      obj.sortid = Math.round(message.sortid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<payItem>, I>>(base?: I): payItem {
    return payItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<payItem>, I>>(object: I): payItem {
    const message = createBasepayItem();
    message.id = object.id ?? 0;
    message.originalGold = object.originalGold ?? 0;
    message.realGold = object.realGold ?? 0;
    message.present = object.present ?? 0;
    message.originalPrice = object.originalPrice ?? 0;
    message.realPrice = object.realPrice ?? 0;
    message.type = object.type ?? 0;
    message.flag = object.flag ?? 0;
    message.discount = object.discount ?? 0;
    message.startTimeStamp = object.startTimeStamp ?? 0;
    message.durationTime = object.durationTime ?? 0;
    message.vip = object.vip ?? 0;
    message.sortid = object.sortid ?? 0;
    return message;
  },
};

function createBasenotifyFalshSale(): notifyFalshSale {
  return { list: [] };
}

export const notifyFalshSale: MessageFns<notifyFalshSale> = {
  encode(message: notifyFalshSale, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.list) {
      payItem.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): notifyFalshSale {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasenotifyFalshSale();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.list.push(payItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): notifyFalshSale {
    return { list: globalThis.Array.isArray(object?.list) ? object.list.map((e: any) => payItem.fromJSON(e)) : [] };
  },

  toJSON(message: notifyFalshSale): unknown {
    const obj: any = {};
    if (message.list?.length) {
      obj.list = message.list.map((e) => payItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<notifyFalshSale>, I>>(base?: I): notifyFalshSale {
    return notifyFalshSale.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<notifyFalshSale>, I>>(object: I): notifyFalshSale {
    const message = createBasenotifyFalshSale();
    message.list = object.list?.map((e) => payItem.fromPartial(e)) || [];
    return message;
  },
};

function createBasecsChargeForCoin(): csChargeForCoin {
  return { id: 0 };
}

export const csChargeForCoin: MessageFns<csChargeForCoin> = {
  encode(message: csChargeForCoin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csChargeForCoin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsChargeForCoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csChargeForCoin {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: csChargeForCoin): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csChargeForCoin>, I>>(base?: I): csChargeForCoin {
    return csChargeForCoin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csChargeForCoin>, I>>(object: I): csChargeForCoin {
    const message = createBasecsChargeForCoin();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBasescChargeForCoin(): scChargeForCoin {
  return { code: 0, msg: "" };
}

export const scChargeForCoin: MessageFns<scChargeForCoin> = {
  encode(message: scChargeForCoin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scChargeForCoin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescChargeForCoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scChargeForCoin {
    return {
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: scChargeForCoin): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scChargeForCoin>, I>>(base?: I): scChargeForCoin {
    return scChargeForCoin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scChargeForCoin>, I>>(object: I): scChargeForCoin {
    const message = createBasescChargeForCoin();
    message.code = object.code ?? 0;
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBasecsChargeBuyCoin(): csChargeBuyCoin {
  return { id: 0 };
}

export const csChargeBuyCoin: MessageFns<csChargeBuyCoin> = {
  encode(message: csChargeBuyCoin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csChargeBuyCoin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsChargeBuyCoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csChargeBuyCoin {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: csChargeBuyCoin): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csChargeBuyCoin>, I>>(base?: I): csChargeBuyCoin {
    return csChargeBuyCoin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csChargeBuyCoin>, I>>(object: I): csChargeBuyCoin {
    const message = createBasecsChargeBuyCoin();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBasescChargeBuyCoin(): scChargeBuyCoin {
  return { code: 0, msg: "" };
}

export const scChargeBuyCoin: MessageFns<scChargeBuyCoin> = {
  encode(message: scChargeBuyCoin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scChargeBuyCoin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescChargeBuyCoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scChargeBuyCoin {
    return {
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: scChargeBuyCoin): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scChargeBuyCoin>, I>>(base?: I): scChargeBuyCoin {
    return scChargeBuyCoin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scChargeBuyCoin>, I>>(object: I): scChargeBuyCoin {
    const message = createBasescChargeBuyCoin();
    message.code = object.code ?? 0;
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBasecsChargeHistroy(): csChargeHistroy {
  return { number: 0, page: 0, day: 0 };
}

export const csChargeHistroy: MessageFns<csChargeHistroy> = {
  encode(message: csChargeHistroy, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.number !== 0) {
      writer.uint32(8).int32(message.number);
    }
    if (message.page !== 0) {
      writer.uint32(16).int32(message.page);
    }
    if (message.day !== 0) {
      writer.uint32(24).int32(message.day);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): csChargeHistroy {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasecsChargeHistroy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.number = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.day = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): csChargeHistroy {
    return {
      number: isSet(object.number) ? globalThis.Number(object.number) : 0,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      day: isSet(object.day) ? globalThis.Number(object.day) : 0,
    };
  },

  toJSON(message: csChargeHistroy): unknown {
    const obj: any = {};
    if (message.number !== 0) {
      obj.number = Math.round(message.number);
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.day !== 0) {
      obj.day = Math.round(message.day);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<csChargeHistroy>, I>>(base?: I): csChargeHistroy {
    return csChargeHistroy.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<csChargeHistroy>, I>>(object: I): csChargeHistroy {
    const message = createBasecsChargeHistroy();
    message.number = object.number ?? 0;
    message.page = object.page ?? 0;
    message.day = object.day ?? 0;
    return message;
  },
};

function createBasescChargeHistroy(): scChargeHistroy {
  return { list: [] };
}

export const scChargeHistroy: MessageFns<scChargeHistroy> = {
  encode(message: scChargeHistroy, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.list) {
      chargeRecord.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scChargeHistroy {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescChargeHistroy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.list.push(chargeRecord.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scChargeHistroy {
    return {
      list: globalThis.Array.isArray(object?.list) ? object.list.map((e: any) => chargeRecord.fromJSON(e)) : [],
    };
  },

  toJSON(message: scChargeHistroy): unknown {
    const obj: any = {};
    if (message.list?.length) {
      obj.list = message.list.map((e) => chargeRecord.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scChargeHistroy>, I>>(base?: I): scChargeHistroy {
    return scChargeHistroy.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scChargeHistroy>, I>>(object: I): scChargeHistroy {
    const message = createBasescChargeHistroy();
    message.list = object.list?.map((e) => chargeRecord.fromPartial(e)) || [];
    return message;
  },
};

function createBasechargeRecord(): chargeRecord {
  return { orderNo: "", coins: 0, orderTime: 0, amount: 0, state: 0, csUrl: "", payUrl: "", typeId: 0, name: "" };
}

export const chargeRecord: MessageFns<chargeRecord> = {
  encode(message: chargeRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderNo !== "") {
      writer.uint32(10).string(message.orderNo);
    }
    if (message.coins !== 0) {
      writer.uint32(16).int64(message.coins);
    }
    if (message.orderTime !== 0) {
      writer.uint32(24).int32(message.orderTime);
    }
    if (message.amount !== 0) {
      writer.uint32(32).int64(message.amount);
    }
    if (message.state !== 0) {
      writer.uint32(40).int32(message.state);
    }
    if (message.csUrl !== "") {
      writer.uint32(50).string(message.csUrl);
    }
    if (message.payUrl !== "") {
      writer.uint32(58).string(message.payUrl);
    }
    if (message.typeId !== 0) {
      writer.uint32(64).int32(message.typeId);
    }
    if (message.name !== "") {
      writer.uint32(74).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): chargeRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasechargeRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderNo = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.coins = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.orderTime = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.state = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.csUrl = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.payUrl = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.typeId = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): chargeRecord {
    return {
      orderNo: isSet(object.orderNo) ? globalThis.String(object.orderNo) : "",
      coins: isSet(object.coins) ? globalThis.Number(object.coins) : 0,
      orderTime: isSet(object.orderTime) ? globalThis.Number(object.orderTime) : 0,
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      state: isSet(object.state) ? globalThis.Number(object.state) : 0,
      csUrl: isSet(object.csUrl) ? globalThis.String(object.csUrl) : "",
      payUrl: isSet(object.payUrl) ? globalThis.String(object.payUrl) : "",
      typeId: isSet(object.typeId) ? globalThis.Number(object.typeId) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: chargeRecord): unknown {
    const obj: any = {};
    if (message.orderNo !== "") {
      obj.orderNo = message.orderNo;
    }
    if (message.coins !== 0) {
      obj.coins = Math.round(message.coins);
    }
    if (message.orderTime !== 0) {
      obj.orderTime = Math.round(message.orderTime);
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.state !== 0) {
      obj.state = Math.round(message.state);
    }
    if (message.csUrl !== "") {
      obj.csUrl = message.csUrl;
    }
    if (message.payUrl !== "") {
      obj.payUrl = message.payUrl;
    }
    if (message.typeId !== 0) {
      obj.typeId = Math.round(message.typeId);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<chargeRecord>, I>>(base?: I): chargeRecord {
    return chargeRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<chargeRecord>, I>>(object: I): chargeRecord {
    const message = createBasechargeRecord();
    message.orderNo = object.orderNo ?? "";
    message.coins = object.coins ?? 0;
    message.orderTime = object.orderTime ?? 0;
    message.amount = object.amount ?? 0;
    message.state = object.state ?? 0;
    message.csUrl = object.csUrl ?? "";
    message.payUrl = object.payUrl ?? "";
    message.typeId = object.typeId ?? 0;
    message.name = object.name ?? "";
    return message;
  },
};

function createBasescGetFirstGift(): scGetFirstGift {
  return { result: 0 };
}

export const scGetFirstGift: MessageFns<scGetFirstGift> = {
  encode(message: scGetFirstGift, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.result !== 0) {
      writer.uint32(8).int32(message.result);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scGetFirstGift {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescGetFirstGift();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.result = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scGetFirstGift {
    return { result: isSet(object.result) ? globalThis.Number(object.result) : 0 };
  },

  toJSON(message: scGetFirstGift): unknown {
    const obj: any = {};
    if (message.result !== 0) {
      obj.result = Math.round(message.result);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scGetFirstGift>, I>>(base?: I): scGetFirstGift {
    return scGetFirstGift.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scGetFirstGift>, I>>(object: I): scGetFirstGift {
    const message = createBasescGetFirstGift();
    message.result = object.result ?? 0;
    return message;
  },
};

function createBasescFirstGiftInfoMsg(): scFirstGiftInfoMsg {
  return { giftID: 0, giftDesc: "" };
}

export const scFirstGiftInfoMsg: MessageFns<scFirstGiftInfoMsg> = {
  encode(message: scFirstGiftInfoMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.giftID !== 0) {
      writer.uint32(8).int32(message.giftID);
    }
    if (message.giftDesc !== "") {
      writer.uint32(18).string(message.giftDesc);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scFirstGiftInfoMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescFirstGiftInfoMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.giftID = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.giftDesc = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scFirstGiftInfoMsg {
    return {
      giftID: isSet(object.giftID) ? globalThis.Number(object.giftID) : 0,
      giftDesc: isSet(object.giftDesc) ? globalThis.String(object.giftDesc) : "",
    };
  },

  toJSON(message: scFirstGiftInfoMsg): unknown {
    const obj: any = {};
    if (message.giftID !== 0) {
      obj.giftID = Math.round(message.giftID);
    }
    if (message.giftDesc !== "") {
      obj.giftDesc = message.giftDesc;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scFirstGiftInfoMsg>, I>>(base?: I): scFirstGiftInfoMsg {
    return scFirstGiftInfoMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scFirstGiftInfoMsg>, I>>(object: I): scFirstGiftInfoMsg {
    const message = createBasescFirstGiftInfoMsg();
    message.giftID = object.giftID ?? 0;
    message.giftDesc = object.giftDesc ?? "";
    return message;
  },
};

function createBasescPayitemBaseInfoMsg(): scPayitemBaseInfoMsg {
  return { list: [] };
}

export const scPayitemBaseInfoMsg: MessageFns<scPayitemBaseInfoMsg> = {
  encode(message: scPayitemBaseInfoMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.list) {
      payItem.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): scPayitemBaseInfoMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasescPayitemBaseInfoMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.list.push(payItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): scPayitemBaseInfoMsg {
    return { list: globalThis.Array.isArray(object?.list) ? object.list.map((e: any) => payItem.fromJSON(e)) : [] };
  },

  toJSON(message: scPayitemBaseInfoMsg): unknown {
    const obj: any = {};
    if (message.list?.length) {
      obj.list = message.list.map((e) => payItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<scPayitemBaseInfoMsg>, I>>(base?: I): scPayitemBaseInfoMsg {
    return scPayitemBaseInfoMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<scPayitemBaseInfoMsg>, I>>(object: I): scPayitemBaseInfoMsg {
    const message = createBasescPayitemBaseInfoMsg();
    message.list = object.list?.map((e) => payItem.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
